# Use the latest Rust version for building
FROM rust:latest AS builder

WORKDIR /app

# Ensure Rust is up-to-date
RUN rustup update stable && rustup default stable

COPY ./crypto_tracker/ ./crypto_tracker/

# Pre-fetch dependencies
WORKDIR /app/crypto_tracker
RUN cargo fetch

# Build the project in release mode
RUN cargo build --release

# Final stage
FROM debian:bookworm

RUN apt-get update && apt-get install -y libssl3 ca-certificates && rm -rf /var/lib/apt/lists/*

WORKDIR /app
COPY --from=builder /app/crypto_tracker/target/release/crypto_tracker .

EXPOSE 9081
CMD ["./crypto_tracker"]