
services:
  web:
    image: nginx:alpine
    volumes:
      - ./public:/usr/share/nginx/html  # Mount the public folder for real-time editing
    expose:
      - 80  # Correctly exposing port 80 to other services in the same network
    networks:
      - my_network  # Add the service to the defined network

  caddy:
    image: caddy:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - web
    networks:
      - my_network  # Add the service to the defined network

  # Backend
  backend:
    build: ./backend  # Dockerfile will be in the backend directory
    #volumes:
    #  - ./backend:/app  # Mount the backend code for real-time editing
    depends_on:
      - postgres  # Ensure PostgreSQL starts before backend
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      POSTGRES_DB: ${POSTGRES_DB:-mydatabase}
    ports:
      - "9080:9080"  # Expose for backend API or services if needed (adjust if necessary)
    # command: ./build/service/BasicService
    networks:
      - my_network  # Add the service to the defined network

  # Rust Backend
  rust_backend:
    build: ./rust_backend  # Use the correct directory for Rust backend
    #volumes:
    #  - ./rust_backend/crypto_tracker:/app/crypto_tracker  # Mount only source code
    depends_on:
      - postgres  # Ensure PostgreSQL starts before Rust backend
    environment:
      DATABASE_URL: postgres://user:password@postgres:5432/mydatabase
      RUST_LOG: info
    ports:
      - "9081:9081"  # Expose Rust backend API
    networks:
      - my_network  # Add the service to the defined network

  # PostgreSQL Database
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      POSTGRES_DB: ${POSTGRES_DB:-mydatabase}
    volumes:
      - pg_data:/var/lib/postgresql/data
    expose:
      - 5432  # Expose PostgreSQL database port
    networks:
      - my_network  # Add the service to the defined network

volumes:
  caddy_data:
  caddy_config:
  pg_data:

networks:
  my_network:
    driver: bridge  # Explicitly define a network (bridge is default)